name: Update template repos

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update template javascript
      uses: dmnemec/copy_file_to_another_repo_action@6e334d9
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'dist/template.v2.js*'
        destination_repo: 'journalovi/jovi_template_html'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'Update template javascript'

    - name: Update template javascript
      uses: dmnemec/copy_file_to_another_repo_action@6e334d9
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'examples/*'
        destination_repo: 'journalovi/jovi_template_html'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'Update template paper'
